"""
gen_cec2011_table.py — generate image_latex/table_cec2011.tex from the raw
CEC2011 real-world results (paper_artifacts/results/cec2011_results.json).
Mean (std) over 30 runs at the full 10^4*d budget; best mean per row in bold.
"""
import json, os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', '..', 'paper_artifacts', 'results',
                   'cec2011_results.json')
DST = os.path.join(HERE, 'image_latex', 'table_cec2011.tex')

ALGOS = ['EGRO-CMA', 'CMA-ES', 'L-SHADE', 'DE', 'PSO', 'GWO', 'WOA']
PROBS = [('FM sound-wave estimation',      'FM parameter estimation'),
         ('Radar polyphase code design',   'Radar polyphase design'),
         ('Lennard-Jones cluster (N=10)',  'Lennard-Jones ($N{=}10$)'),
         ('Lennard-Jones cluster (N=15)',  'Lennard-Jones ($N{=}15$)')]

res = json.load(open(SRC))


def cell(v, s, bold):
    m = f"{v:.3g}"
    if 'e' in m:                       # avoid exponent notation at these scales
        m = f"{v:.2f}"
    # math mode for proper minus signs; \mathbf, since \textbf does not
    # bold anything inside $...$
    m = f"$\\mathbf{{{m}}}$" if bold else f"${m}$"
    return f"{m} {{\\scriptsize({s:.2g})}}"


rows = []
for key, label in PROBS:
    d = next(r['n'] for r in res.values() if r['problem'] == key)
    fb = next(r['f_best'] for r in res.values() if r['problem'] == key)
    stats = {}
    for a in ALGOS:
        v = np.array([r['budget'][max(r['budget'], key=lambda k: int(k))]
                      for r in res.values()
                      if r['problem'] == key and r['algo'] == a])
        assert len(v) == 30, (key, a, len(v))
        stats[a] = (v.mean(), v.std())
    best = min(ALGOS, key=lambda a: stats[a][0])
    fbs = f"${fb:.4g}$" if fb else "$0$"
    cells = " & ".join(cell(*stats[a], bold=(a == best)) for a in ALGOS)
    rows.append(f"    {label} & {d} & {fbs} & {cells} \\\\")

table = r"""%% Auto-generated by gen_cec2011_table.py — do not edit by hand.
\begin{table*}[!t]
  \centering
  \caption{Real-world problems: mean (std) of the best objective value over
           $30$ independent runs under the $10^4 d$ FE budget, with the
           best-known value $f^{\rm best}$ of each problem for reference
           (FM and radar from the CEC~2011 suite~\cite{Das2010};
           Lennard-Jones minima from basin-hopping~\cite{Wales1997}).
           Bold marks the best mean per row.}
  \label{tab:cec2011}
  \small
  \setlength{\tabcolsep}{4.5pt}
  \begin{tabular}{l c r ccccccc}
    \toprule
    Problem & $d$ & $f^{\rm best}$ &
    EGRO-CMA & CMA-ES & L-SHADE & DE & PSO & GWO & WOA \\
    \midrule
""" + "\n".join(rows) + r"""
    \bottomrule
  \end{tabular}
\end{table*}
"""

open(DST, 'w', encoding='utf-8').write(table)
print("wrote", DST)
