"""
gen_robustness_table.py — sensitivity of the CEC ranking to the functions
whose implementation reference is inconsistent.

For each dimension the tie-aware Friedman ranks are recomputed twice: over
every evaluable function, and over only those functions on which no algorithm
records a negative error (i.e. whose declared optimum is consistent with the
coded surface).  Emits table_robustness.tex and prints the comparison.

Usage:  python gen_robustness_table.py [src_dir] [out_dir]
"""
import json
import os
import sys

import numpy as np

from gen_official_tables import ALGOS, DIMS, ETOL, tie_ranks


def load_means(path):
    """Return (means, affected) for one dimension file."""
    data = json.load(open(path))
    means, affected = {}, set()
    for key, rec in data.items():
        if key == '_meta':
            continue
        row, ok = {}, True
        for a in ALGOS:
            arec = rec.get(a)
            errs = [0.0 if abs(e) < ETOL else e
                    for e in (arec or {}).get('errors', []) if e is not None]
            if arec is None or len(errs) < len(arec['errors']):
                ok = False
                break
            row[a] = float(np.mean(errs))
            if min(errs) < -ETOL:
                affected.add(key)
        if ok:
            means[key] = row
    return means, affected


def mean_ranks(means, keys):
    R = np.array([tie_ranks([means[f][a] for a in ALGOS]) for f in keys])
    return dict(zip(ALGOS, R.mean(axis=0)))


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else '.'
    dst = sys.argv[2] if len(sys.argv) > 2 else src
    cols, counts, excluded = {}, {}, {}

    for dim in DIMS:
        path = os.path.join(src, 'cec2017_official_d%d.json' % dim)
        if not os.path.exists(path):
            continue
        means, affected = load_means(path)
        allk = sorted(means, key=lambda s: int(s[1:]))
        clean = [k for k in allk if k not in affected]
        cols[dim] = (mean_ranks(means, allk), mean_ranks(means, clean))
        counts[dim] = (len(allk), len(clean))
        excluded[dim] = sorted(affected, key=lambda s: int(s[1:]))
        print('d=%-3d all n=%-3d clean n=%-3d  excluded: %s'
              % (dim, len(allk), len(clean), ', '.join(excluded[dim])))
        for lbl, r in (('all  ', cols[dim][0]), ('clean', cols[dim][1])):
            print('     %s %s' % (lbl, '  '.join(
                '%s %.2f' % (a, r[a]) for a in sorted(ALGOS, key=r.get))))

    dims = sorted(cols)
    L = [
        '%% Auto-generated by gen_robustness_table.py',
        '\\begin{table*}[!t]',
        '  \\centering',
        '  \\caption{Sensitivity of the ranking to the functions whose',
        '           implementation reference is inconsistent',
        '           (Section~\\ref{sec:benchmark}).  Mean tie-aware Friedman',
        '           rank over all evaluable functions (\\emph{all}) and over',
        '           only those with a consistent reference (\\emph{cons.});',
        '           function counts in parentheses.  Lower is better.}',
        '  \\label{tab:robustness}',
        '  \\small',
        '  \\setlength{\\tabcolsep}{4pt}',
        '  \\begin{tabular}{l' + 'rr' * len(dims) + '}',
        '    \\toprule',
        '    & ' + ' & '.join('\\multicolumn{2}{c}{$d = %d$}' % d
                              for d in dims) + ' \\\\',
        '    ' + ' '.join('\\cmidrule(lr){%d-%d}' % (2 + 2 * i, 3 + 2 * i)
                          for i in range(len(dims))),
        '    Algorithm & ' + ' & '.join(
            'all (%d) & cons. (%d)' % counts[d] for d in dims) + ' \\\\',
        '    \\midrule',
    ]
    best_all = {d: min(cols[d][0], key=cols[d][0].get) for d in dims}
    best_cln = {d: min(cols[d][1], key=cols[d][1].get) for d in dims}
    for a in ALGOS:
        cells = []
        for d in dims:
            va, vc = cols[d][0][a], cols[d][1][a]
            cells.append('\\textbf{%.2f}' % va if a == best_all[d]
                         else '%.2f' % va)
            cells.append('\\textbf{%.2f}' % vc if a == best_cln[d]
                         else '%.2f' % vc)
        name = '\\textbf{%s}' % a if a == 'EGRO-CMA' else a
        L.append('    %s & %s \\\\' % (name, ' & '.join(cells)))
    L += ['    \\bottomrule', '  \\end{tabular}', '\\end{table*}']

    out = os.path.join(dst, 'table_robustness.tex')
    open(out, 'w').write('\n'.join(L) + '\n')
    print('wrote', out)


if __name__ == '__main__':
    main()
